
# Loop constraints
directive set /reduce_by_5/core/main CSTEPS_FROM {{. == 1}}
directive set /reduce_by_5/core/main/FRAME CSTEPS_FROM {{. == 16} {.. == 1}}

# IO operation constraints
directive set /reduce_by_5/core/main/FRAME/ACC1:if:io_read(vin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:io_read(vin:rsc.d)#1 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:io_read(vin:rsc.d)#2 CSTEPS_FROM {{.. == 3}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:io_read(vin:rsc.d)#3 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:io_read(vin:rsc.d)#4 CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if#1:io_write(clk_reg:rsc.d)#1 CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if#2:io_write(vout:rsc.d) CSTEPS_FROM {{.. == 15}}

# Real operation constraints
directive set /reduce_by_5/core/main/FRAME/ACC1-1:if:mul CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#19 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#3 CSTEPS_FROM {{.. == 3}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#4 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#17 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#20 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/acc#2 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#22 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#23 CSTEPS_FROM {{.. == 4}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#5 CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/acc#3 CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mux CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/ACC1-1:if:acc CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/ACC1:mux CSTEPS_FROM {{.. == 5}}
directive set /reduce_by_5/core/main/FRAME/ACC1-2:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#9 CSTEPS_FROM {{.. == 6}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#10 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#28 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#31 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/acc#4 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#33 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#34 CSTEPS_FROM {{.. == 7}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#11 CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/acc#5 CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#7 CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mux#1 CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/ACC1-2:if:acc CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/ACC1:mux#1 CSTEPS_FROM {{.. == 8}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#41 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#40 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#43 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#15 CSTEPS_FROM {{.. == 9}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#16 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#39 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#42 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/acc#6 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#44 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#45 CSTEPS_FROM {{.. == 10}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#17 CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/acc#7 CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#8 CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mux#2 CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/ACC1-3:if:acc CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/ACC1:mux#2 CSTEPS_FROM {{.. == 11}}
directive set /reduce_by_5/core/main/FRAME/ACC1-4:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#48 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#46 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#47 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#52 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#51 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#54 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#21 CSTEPS_FROM {{.. == 12}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#22 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#50 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#49 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#53 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/acc#8 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#55 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#56 CSTEPS_FROM {{.. == 13}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#23 CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/acc#9 CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#11 CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mux#3 CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/ACC1-4:if:acc CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/ACC1:mux#3 CSTEPS_FROM {{.. == 14}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#59 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#57 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#58 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#63 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#62 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#65 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#27 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#28 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#61 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#60 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#64 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/acc#10 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#66 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#67 CSTEPS_FROM {{.. == 2}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mul#29 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/acc#11 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:acc#13 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/ACC1:if:mux#4 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/ACC1-5:if:acc CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/ACC1:mux#4 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/acc CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/acc#1 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:if:if:acc CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/FRAME:mux#1 CSTEPS_FROM {{.. == 15}}
directive set /reduce_by_5/core/main/FRAME/FRAME:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:acc CSTEPS_FROM {{.. == 1}}
directive set /reduce_by_5/core/main/FRAME/FRAME:and CSTEPS_FROM {{.. == 15}}
