// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   nn1114@EEWS104A-019
//  Generated date: Tue Mar 24 14:59:33 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    black_white
//  Generated from file(s):
//   15) $PROJECT_HOME/black_white.cpp
// ------------------------------------------------------------------


module black_white (
  output_rsc_z, clk, en, arst_n
);
  output [29:0] output_rsc_z;
  input clk;
  input en;
  input arst_n;



  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(4),
  .width(30)) output_rsc_mgc_out_stdreg (
      .d(30'b100000000010000000001),
      .z(output_rsc_z)
    );
endmodule



