// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   lb3314@EEWS104A-019
//  Generated date: Tue Mar 24 18:40:57 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    edge_core
// ------------------------------------------------------------------


module edge_core (
  clk, en, arst_n, vin_rsc_mgc_in_wire_d, vout_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [89:0] vin_rsc_mgc_in_wire_d;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [7:0] regs_regs_1_sg1_sva;
    reg [7:0] regs_regs_0_sg1_sva;
    reg [7:0] regs_regs_0_sg1_sva_1;
    reg [7:0] ACC2_acc_psp_sva;
    reg [7:0] ACC2_asn_itm;

    begin : core_rlpExit
      forever begin : core_rlp
        // C-Step 0 of Loop 'core_rlp'
        regs_regs_1_sg1_sva = 8'b0;
        regs_regs_0_sg1_sva = 8'b0;
        begin : mainExit
          forever begin : main
            // C-Step 0 of Loop 'main'
            ACC2_asn_itm = regs_regs_1_sg1_sva;
            regs_regs_1_sg1_sva = regs_regs_0_sg1_sva;
            begin : waitLoop0Exit
              forever begin : waitLoop0
                @(posedge clk or negedge ( arst_n ));
                if ( ~ arst_n )
                  disable core_rlpExit;
                if ( en )
                  disable waitLoop0Exit;
              end
            end
            // C-Step 1 of Loop 'main'
            regs_regs_0_sg1_sva_1 = vin_rsc_mgc_in_wire_d[27:20];
            ACC2_acc_psp_sva = readslicef_9_8_1((({(~ regs_regs_0_sg1_sva_1) , 1'b1})
                + ({ACC2_asn_itm , 1'b1})));
            vout_rsc_mgc_out_stdreg_d <= {ACC2_acc_psp_sva , 2'b0 , ACC2_acc_psp_sva
                , 2'b0 , ACC2_acc_psp_sva , 2'b0};
            regs_regs_0_sg1_sva = regs_regs_0_sg1_sva_1;
          end
        end
      end
    end
    ACC2_asn_itm = 8'b0;
    ACC2_acc_psp_sva = 8'b0;
    regs_regs_0_sg1_sva_1 = 8'b0;
    regs_regs_0_sg1_sva = 8'b0;
    regs_regs_1_sg1_sva = 8'b0;
    vout_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [7:0] readslicef_9_8_1;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_9_8_1 = tmp[7:0];
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    edge_0
//  Generated from file(s):
//    4) $PROJECT_HOME/edge.c
// ------------------------------------------------------------------


module edge_0 (
  vin_rsc_z, vout_rsc_z, clk, en, arst_n
);
  input [89:0] vin_rsc_z;
  output [29:0] vout_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [89:0] vin_rsc_mgc_in_wire_d;
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(90)) vin_rsc_mgc_in_wire (
      .d(vin_rsc_mgc_in_wire_d),
      .z(vin_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  edge_core edge_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vin_rsc_mgc_in_wire_d(vin_rsc_mgc_in_wire_d),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



