// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   nn1114@EEWS104A-002
//  Generated date: Wed May 13 16:35:03 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    detect_skin_core
// ------------------------------------------------------------------


module detect_skin_core (
  clk, en, arst_n, pixin_rsc_mgc_in_wire_d, pixout_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [29:0] pixin_rsc_mgc_in_wire_d;
  output [29:0] pixout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  wire [7:0] Cr_sg1_sva_1;
  wire [8:0] nl_Cr_sg1_sva_1;
  wire [7:0] Cb_sg1_sva_1;
  wire [8:0] nl_Cb_sg1_sva_1;
  wire [19:0] acc_sdt_2_sva;
  wire [20:0] nl_acc_sdt_2_sva;
  wire [17:0] acc_11_psp;
  wire [18:0] nl_acc_11_psp;
  wire [19:0] acc_9_sdt;
  wire [20:0] nl_acc_9_sdt;
  reg reg_pixout_rsc_mgc_out_stdreg_d_reg;
  wire [19:0] acc_sdt_sva;
  wire [20:0] nl_acc_sdt_sva;
  wire [17:0] mul_12_sdt;
  wire [35:0] nl_mul_12_sdt;


  // Interconnect Declarations for Component Instantiations 
  assign pixout_rsc_mgc_out_stdreg_d = {{29{reg_pixout_rsc_mgc_out_stdreg_d_reg}},
      reg_pixout_rsc_mgc_out_stdreg_d_reg};
  assign nl_acc_sdt_sva = conv_u2u_19_20(conv_u2u_38_19(19'b100101011 * conv_u2u_10_19(pixin_rsc_mgc_in_wire_d[29:20])))
      + conv_s2u_40_20(20'b1001001011 * conv_u2u_10_20(pixin_rsc_mgc_in_wire_d[19:10]));
  assign acc_sdt_sva = nl_acc_sdt_sva[19:0];
  assign nl_Cr_sg1_sva_1 = (acc_sdt_2_sva[19:12]) + 8'b1111101;
  assign Cr_sg1_sva_1 = nl_Cr_sg1_sva_1[7:0];
  assign nl_acc_sdt_2_sva = ({(conv_u2u_17_18(conv_u2u_34_17(conv_u2u_10_17(pixin_rsc_mgc_in_wire_d[29:20])
      * 17'b1111101)) + conv_s2u_16_18(mul_12_sdt[17:2])) , (mul_12_sdt[1:0])}) +
      conv_u2u_40_20(conv_u2s_10_20(pixin_rsc_mgc_in_wire_d[19:10]) * 20'b11111111111001011101);
  assign acc_sdt_2_sva = nl_acc_sdt_2_sva[19:0];
  assign nl_Cb_sg1_sva_1 = (acc_11_psp[17:10]) + 8'b1111101;
  assign Cb_sg1_sva_1 = nl_Cb_sg1_sva_1[7:0];
  assign nl_acc_11_psp = (acc_9_sdt[19:2]) + conv_u2u_36_18(conv_u2s_10_18(pixin_rsc_mgc_in_wire_d[19:10])
      * 18'b111111111110101101);
  assign acc_11_psp = nl_acc_11_psp[17:0];
  assign nl_acc_9_sdt = conv_u2u_19_20(conv_u2u_38_19(conv_u2u_10_19(pixin_rsc_mgc_in_wire_d[9:0])
      * 19'b111110101)) + conv_s2u_19_20(conv_s2u_38_19(19'b1111111111101010111 *
      conv_u2s_10_19(pixin_rsc_mgc_in_wire_d[29:20])));
  assign acc_9_sdt = nl_acc_9_sdt[19:0];
  assign nl_mul_12_sdt = conv_u2s_10_18(pixin_rsc_mgc_in_wire_d[9:0]) * 18'b111111111110101111;
  assign mul_12_sdt = nl_mul_12_sdt[17:0];
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      reg_pixout_rsc_mgc_out_stdreg_d_reg <= 1'b0;
    end
    else begin
      if ( en ) begin
        reg_pixout_rsc_mgc_out_stdreg_d_reg <= (readslicef_21_1_20((({1'b1 , (~ ((acc_sdt_sva[19:1])
            + conv_u2u_16_19(conv_u2u_32_16(conv_u2u_10_16(pixin_rsc_mgc_in_wire_d[9:0])
            * 16'b111001)))) , (~ (acc_sdt_sva[0]))}) + 21'b1001110010111101001)))
            & (~((readslicef_21_1_20((({1'b1 , (~ Cr_sg1_sva_1) , (~ (acc_sdt_2_sva[11:0]))})
            + 21'b10101001101011011001))) | (readslicef_17_1_16((conv_u2u_16_17({Cr_sg1_sva_1
            , (acc_sdt_2_sva[11:4])}) + 17'b10111110110100001))) | (readslicef_21_1_20((({1'b1
            , (~ Cb_sg1_sva_1) , (~ (acc_11_psp[9:0])) , (~ (acc_9_sdt[1:0]))}) +
            21'b1111100100000110001))) | (readslicef_18_1_17((conv_u2u_17_18({Cb_sg1_sva_1
            , (acc_11_psp[9:1])}) + 18'b110110100100011111)))));
      end
    end
  end

  function [0:0] readslicef_21_1_20;
    input [20:0] vector;
    reg [20:0] tmp;
  begin
    tmp = vector >> 20;
    readslicef_21_1_20 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_17_1_16;
    input [16:0] vector;
    reg [16:0] tmp;
  begin
    tmp = vector >> 16;
    readslicef_17_1_16 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_18_1_17;
    input [17:0] vector;
    reg [17:0] tmp;
  begin
    tmp = vector >> 17;
    readslicef_18_1_17 = tmp[0:0];
  end
  endfunction


  function  [19:0] conv_u2u_19_20 ;
    input [18:0]  vector ;
  begin
    conv_u2u_19_20 = {1'b0, vector};
  end
  endfunction


  function  [18:0] conv_u2u_38_19 ;
    input [37:0]  vector ;
  begin
    conv_u2u_38_19 = vector[18:0];
  end
  endfunction


  function  [18:0] conv_u2u_10_19 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_19 = {{9{1'b0}}, vector};
  end
  endfunction


  function  [19:0] conv_s2u_40_20 ;
    input signed [39:0]  vector ;
  begin
    conv_s2u_40_20 = vector[19:0];
  end
  endfunction


  function  [19:0] conv_u2u_10_20 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_20 = {{10{1'b0}}, vector};
  end
  endfunction


  function  [17:0] conv_u2u_17_18 ;
    input [16:0]  vector ;
  begin
    conv_u2u_17_18 = {1'b0, vector};
  end
  endfunction


  function  [16:0] conv_u2u_34_17 ;
    input [33:0]  vector ;
  begin
    conv_u2u_34_17 = vector[16:0];
  end
  endfunction


  function  [16:0] conv_u2u_10_17 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_17 = {{7{1'b0}}, vector};
  end
  endfunction


  function  [17:0] conv_s2u_16_18 ;
    input signed [15:0]  vector ;
  begin
    conv_s2u_16_18 = {{2{vector[15]}}, vector};
  end
  endfunction


  function  [19:0] conv_u2u_40_20 ;
    input [39:0]  vector ;
  begin
    conv_u2u_40_20 = vector[19:0];
  end
  endfunction


  function signed [19:0] conv_u2s_10_20 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_20 = {{10{1'b0}}, vector};
  end
  endfunction


  function  [17:0] conv_u2u_36_18 ;
    input [35:0]  vector ;
  begin
    conv_u2u_36_18 = vector[17:0];
  end
  endfunction


  function signed [17:0] conv_u2s_10_18 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_18 = {{8{1'b0}}, vector};
  end
  endfunction


  function  [19:0] conv_s2u_19_20 ;
    input signed [18:0]  vector ;
  begin
    conv_s2u_19_20 = {vector[18], vector};
  end
  endfunction


  function  [18:0] conv_s2u_38_19 ;
    input signed [37:0]  vector ;
  begin
    conv_s2u_38_19 = vector[18:0];
  end
  endfunction


  function signed [18:0] conv_u2s_10_19 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_19 = {{9{1'b0}}, vector};
  end
  endfunction


  function  [18:0] conv_u2u_16_19 ;
    input [15:0]  vector ;
  begin
    conv_u2u_16_19 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [15:0] conv_u2u_32_16 ;
    input [31:0]  vector ;
  begin
    conv_u2u_32_16 = vector[15:0];
  end
  endfunction


  function  [15:0] conv_u2u_10_16 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_16 = {{6{1'b0}}, vector};
  end
  endfunction


  function  [16:0] conv_u2u_16_17 ;
    input [15:0]  vector ;
  begin
    conv_u2u_16_17 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    detect_skin
//  Generated from file(s):
//    2) $PROJECT_HOME/skin.c
// ------------------------------------------------------------------


module detect_skin (
  pixin_rsc_z, pixout_rsc_z, clk, en, arst_n
);
  input [29:0] pixin_rsc_z;
  output [29:0] pixout_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] pixin_rsc_mgc_in_wire_d;
  wire [29:0] pixout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(30)) pixin_rsc_mgc_in_wire (
      .d(pixin_rsc_mgc_in_wire_d),
      .z(pixin_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) pixout_rsc_mgc_out_stdreg (
      .d(pixout_rsc_mgc_out_stdreg_d),
      .z(pixout_rsc_z)
    );
  detect_skin_core detect_skin_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .pixin_rsc_mgc_in_wire_d(pixin_rsc_mgc_in_wire_d),
      .pixout_rsc_mgc_out_stdreg_d(pixout_rsc_mgc_out_stdreg_d)
    );
endmodule



